version: '3.8'

services:
  # Nginxリバースプロキシ
  nginx:
    build: ./nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  # バックエンドAPI
  backend:
    build: ./backend
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
      - ./module:/app/module
      - ./prompt:/app/prompt
      - ./schema:/app/schema
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --timeout-keep-alive 120

  # フロントエンド
  frontend:
    build:
      context: ./react-app
      target: development
    environment:
      - VITE_API_URL=/api
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    volumes:
      - ./react-app:/app
      - /app/node_modules
    networks:
      - app-network
    command: npm run dev -- --host 0.0.0.0

networks:
  app-network:
    driver: bridge