SUPABASE_URL = "https://wttynclovrmxlbbdxzcd.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0dHluY2xvdnJteGxiYmR4emNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0Nzk0NjUsImV4cCI6MjA2MDA1NTQ2NX0.sr29xirQB0_GEOpUe17kZbedvO4lQNwy_fRxUuWhfeE"

[theme]
primaryColor = "#73bbff"